### ISSUE TITLE
Faire fonctionner l'intégration continue

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#1]
Faire fonctionner le pipeline de build de bout en bout : 
- Intégrer github et travisCI
- Créer une première version l'application avec Rails
- La commiter et la remonter vers github
- Vérifier que les tests passent
- Déployer sur heroku

**Comment by LPA2-Automne2016** [comment]
Régler le problème sous travis : 
créer le travis.yml, désactiver ruby 1.9.3 et vérfier que le build fonctionne.

à l'issue : poster ici le lien vers votre build travis

**Comment by Transrian** [comment]
Voici le lien de mon build travis fonctionnel : https://travis-ci.org/Transrian/projet/jobs/210093555
Valentin Bourdier

**Comment by lisamaison** [comment]
Bonjour, voici également le lien de mon build : https://travis-ci.org/lisamaison/projet/builds/210257938
Bessone Lisa

**Comment by quentinpmf** [comment]
Bonjour, ci-joint le lien de mon build fonctionnel : https://travis-ci.org/quentinpmf/projet/builds/210237919 
Quentin Boudinot.

**Comment by Globuss** [comment]
Bonjour, ci joint le lien de mon build fonctionnel : https://travis-ci.org/Globuss/projet/builds/210238451
Théo Pierret

**Comment by quentinpmf** [comment]
Bonjour, ci-joint le lien de mon build fonctionnel : https://travis-ci.org/quentinpmf/projet/builds/210873430
Quentin Boudinot.

**Comment by MeyerEsther** [comment]
Bonjour, voici le lien de mon build fonctionnel: https://travis-ci.org/MeyerEsther/projet/builds/210680445
Meyer Esther

**Comment by Aurelien-Py** [comment]
Bonjour, voici le lien de mon build fonctionnel: https://travis-ci.org/Aurelien-Py/projet/jobs/210868954
PY Aurélien

**Comment by lisamaison** [comment]
Bonjour, j'ai modifié mon build pour avoir la version 2.3.0 de RUBY : https://travis-ci.org/lisamaison/projet/builds/210877628
Bessone Lisa

**Comment by thibaut-monrouzeau** [comment]
Bonjour, lien de mon build : https://travis-ci.org/thibaut-monrouzeau/projet/jobs/210878054
Thibaut Monrouzeau

**Comment by remipe-utbm** [comment]
Bonjour, ci-joint le lien de mon build fonctionnel en 2.3.0 : https://travis-ci.org/remipe-utbm/projet/jobs/210885697

Rémi Pereira

**Comment by Sgliere** [comment]
Bonjour, Voici mon build fonctionnel pour les version 2.2 et 2.2.4 : https://travis-ci.org/Sgliere/projet/builds/210889333

Swann Gliere

**Comment by sye9286** [comment]
Bonjour, voici mon lien : https://travis-ci.org/sye9286/projet/jobs/211435390

Sheng YE

**Comment by VMoniz** [comment]
Bonjour, voici le lien : https://travis-ci.org/VMoniz/projet/jobs/211463830

Valentine Moniz

**Comment by QuentinSimonU** [comment]
Bonjour, voici mon lien : https://travis-ci.org/QuentinSimonU/projet/jobs/210028400

Quentin Simon

**Comment by Katravan** [comment]
Bonjour, voici le lien pour mon build : https://travis-ci.org/Katravan/projet/builds/211641046
Florian Inard

**Comment by alexandrebm74** [comment]
Bonjour Sebastien,

J'étais absent samedi dernier.

Mes collègues m'ont aidé à rattraper ce que vous aviez fait.

Voici le lien de mon build : https://travis-ci.org/alexandrebm74/projet/builds/211816290

Cdt,

Alexandre BOURDILLAS-MACEY.

**Comment by NBarras** [comment]
Bonjour, 

Voici le lien de mon build : https://travis-ci.org/NBarras/projet/builds/212213985

Cordialement,
Noé Barras

**Comment by dlcadrien** [comment]
Bonjour, voici le lien pour mon build fonctionnel : https://travis-ci.org/dlcadrien/projet/builds/210939267
Adrien Delcourt

**Comment by jacmartinelli** [comment]
bonjour, voici le lien pour build fonctionnel: https://travis-ci.org/jacmartinelli/projet/builds/212258034 
Jacques Martinelli

**Comment by GuillaumePriou** [comment]
Bonjour, voici le lien vers mon build fonctionnel : https://travis-ci.org/GuillaumePriou/projet/builds/212274996
Guillaume Priou

**Comment by LPA2-Automne2016** [comment]
Bravo à tous,
tout fonctionne impeccable !
