### ISSUE TITLE
Faire fonctionner l'intégration continue

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#1]
Faire fonctionner le pipeline de build de bout en bout : 

- [ ] Intégrer github et travisCI
- [ ] Créer une première version l'application avec Rails
- [ ] La commiter et la remonter vers github
- [ ] Vérifier que les tests passent
- [ ] déployer sur heroku

**Comment by LPA2-Automne2016** [comment]
comment marche git 
https://services.github.com/kit/downloads/fr/github-git-cheat-sheet.pdf

en résumé 
```
# verifier que l'appli se lance
git add .
git commit (editer le message et ESC + :wq pour ecrire quitter)
git push
```

creer l'application dans heroku
https://devcenter.heroku.com/articles/getting-started-with-ruby

configurer travis
https://docs.travis-ci.com/user/deployment/heroku/

ajouter l'url de votre application en commenta

**Comment by aomnes** [comment]
https://intense-depths-17257.herokuapp.com/students/
Voici mon lien de mon site sur Heroku avec l'utilisateur de Postgresql seulement (sans sqlite3) validation sur Travis-ci.
J'espère que tous les paramètres sont bien réglés.

**Comment by LPA2-Automne2016** [comment]
@aomnes tres beau boulot : intégration fonctionnelle : https://travis-ci.org/aomnes/appli_pg/builds/162908496

L'appli fonctionne.

**Comment by dsyouness** [comment]
Lien sur Heroku : https://murmuring-springs-27327.herokuapp.com/students
Lien Travis : https://travis-ci.org/dsyouness/projet

"L'utilisation de Postgresql au lieu de sqlite3 fonctionne correctement et valider par Travis."

**Comment by HuangMichel** [comment]
https://travis-ci.org/HuangMichel/projet/jobs/164229401
https://studentliste.herokuapp.com/students

Voici mon lien de Travis et de l'application.

**Comment by LPA2-Automne2016** [comment]
bonjour @HuangMichel, impeccable, tout fonctionne.

**Comment by oacardoso** [comment]
https://shielded-temple-37883.herokuapp.com/students
https://travis-ci.org/oacardoso/Work-Student/builds/164434277
Voila mes liens de l'application et de Travis

**Comment by LPA2-Automne2016** [comment]
bonsoir @oacardoso !
Tout est OK, merci

**Comment by xAlban** [comment]
https://salty-fortress-48990.herokuapp.com/students
https://travis-ci.org/xAlban/projet/builds/164579798
Bonjour, voici les deux liens (Application + Travis).

**Comment by LPA2-Automne2016** [comment]
bonsoir @xAlban,
ton CI ne déploie pas directement dans Heroku.
C'est probablement déployé à la main, mais la boule entiere n'est pas bouclée (sauf si tu es passé depuis github au lieu de travis)

**Comment by safaael** [comment]
Bonsoir! 
https://travis-ci.org/safaael/projet
https://gentle-peak-77971.herokuapp.com/students

**Comment by assaadkenaan** [comment]
Bonsoir !
Voici les deux liens ( Travis + Heroku )

https://travis-ci.org/assaadkenaan/projet
https://agile-island-78481.herokuapp.com/students

**Comment by LPA2-Automne2016** [comment]
Bonsoir @assaadkenaan, Attention : ce n'est pas travis qui a déployé vers Heroku
ton pipeline n'est pas terminé !

**Comment by assaadkenaan** [comment]
Bonjour,

 https://travis-ci.org/assaadkenaan/projet

https://agile-island-78481.herokuapp.com/students

j'espère que ca marche maintenant !

**Comment by WEI-Jialiang** [comment]
Bonsoir! Voici les deux liens.
https://travis-ci.org/WEI-Jialiang/projet/jobs/165355893
https://immense-harbor-17013.herokuapp.com/students

**Comment by ASARIR** [comment]
https://radiant-dusk-68990.herokuapp.com/students/

**Comment by cfall** [comment]
Bonsoir, 
lien de mon appli 
https://travis-ci.org/cfall/projet_LPA2/
https://secure-ocean-53691.herokuapp.com/users

**Comment by MaoYiwen** [comment]
Bonjour ! J'ai fini le devoir.
https://evening-woodland-43494.herokuapp.com/students
https://travis-ci.org/MaoYiwen/projet/jobs/165836683

**Comment by LPA2-Automne2016** [comment]
bonsoir @cfall,
Attention ton intégration continue ne livre pas heroku comme demandé.

**Comment by wnansseu** [comment]
voici mon application
https://travis-ci.org/wnansseu/projet
https://agile-temple-60827.herokuapp.com/students

**Comment by LIUJINGYUYVES** [comment]
https://travis-ci.org/LIUJINGYUYVES/projet/jobs/166074239
https://aqueous-shore-60208.herokuapp.com/students
Voici mon lien de Travis et de l'application.

**Comment by qxj1210** [comment]
Bonsoir, voici mon lien de Travis et de l'application
https://travis-ci.org/qxj1210/projet/jobs/166099691
https://pacific-castle-52755.herokuapp.com

**Comment by xiaoma27** [comment]
Bonsoir, 
c'est mon lien de l'application et de Travis.
https://pacific-ridge-98926.herokuapp.com
https://pure-savannah-64144.herokuapp.com/students

**Comment by zeyizhou** [comment]
Bonsoir,
c'est mon lien de l'application et de Travis
https://dry-beach-94025.herokuapp.com/
https://travis-ci.org/zeyizhou/projet/branches

**Comment by jwang04** [comment]
Bonsoir,
lien de mon appli 
https://travis-ci.org/jwang04/projet
https://fierce-mesa-66693.herokuapp.com/students

**Comment by echoise** [comment]
Bonsoir,
c'est mon lien de l'application et de Travis
https://obscure-mesa-45326.herokuapp.com/students
https://travis-ci.org/echoise/projet/jobs/166234689
mais pour le travis-ci, il y a des erreurs.
/home/travis/build.sh: line 45: heroku: command not found
invalid option "--api_key="
failed to deploy
Comment je peux résoudre ce problème?
@LPA2-Automne2016

**Comment by Yzxwyydn** [comment]
Bonsoir,
c'est mon lien de l'application et de Travis
https://gentle-dawn-35479.herokuapp.com/students/1
https://travis-ci.org/Yzxwyydn/projet/jobs/166230445
Pour le travis-ci,il y a un problème de /home/travis/build.sh: line 45: heroku: command not found
invalid option "--api_key="
failed to deploy
Comment résoudre ça? @LPA2-Automne2016

**Comment by YUZHENFEI** [comment]
Voici les deux liens
https://travis-ci.org/YUZHENFEI/projet/branches
https://desolate-meadow-89650.herokuapp.com/students

**Comment by MARui22** [comment]
https://mysterious-hollows-64927.herokuapp.com/students/1
https://travis-ci.org/MARui22/projet/branches

je finis le devoir!!

**Comment by juyulu** [comment]
voici les liens de mes devoirs:
https://travis-ci.org/juyulu/projet/branches
https://sheltered-mountain-28734.herokuapp.com/students/1

**Comment by Zilliq11** [comment]
Bonsoir,
voici mon lien Travis : https://travis-ci.org/Zilliq11/projet
et mon lien Heroku : http://lpa2-zilliq11.herokuapp.com/students
Bonne soirée!

**Comment by LPA2-Automne2016** [comment]
@echoise @Yzxwyydn  votre clef API n'est probablement pas la bonne !
En case de problème, utilisez plutôt https://lpa2.slack.com pour communiquer, cela sera plus facile

**Comment by LPA2-Automne2016** [comment]
@Zilliq11 je vois que la bonne vieille tradition des devoirs à l'arrache n'a pas disparue....

**Comment by Zilliq11** [comment]
![a l arrache mais pas trop](https://cloud.githubusercontent.com/assets/9016031/19248134/8ec543b8-8f2e-11e6-8241-a2cd4e10765f.PNG)
Oui, cela reste néanmoins modéré. :)

**Comment by med-amiine** [comment]
Bonsoir,
Travis : https://travis-ci.org/med-amiine/projet
Heroku : https://secret-sierra-80991.herokuapp.com/students/

**Comment by mtetou** [comment]
lien Travis: https://travis-ci.org/mtetou/projet
lien Heroku: https://radiant-refuge-58204.herokuapp.com/students
