### ISSUE TITLE
activation Intégration continue

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#1]
activer l'intégration continue sur travis CI et faire passer les tests.

https://travis-ci.org/

Soumettre en commentaire l'url vers votre test d'intégration travis qui fonctionne:
exemple: 
https://travis-ci.org/studio1247/gertrude/builds/278907647

Pour y arriver : activer le projet dans travis, créer le .travis.yml, pousser le code vers github

**Comment by Anthex** [comment]
https://travis-ci.org/Anthex/projet/builds/278909947

**Comment by FlorianR-UTBM** [comment]
https://travis-ci.org/FlorianR-UTBM/projet/builds/278910094

**Comment by FlorianParty** [comment]
https://travis-ci.org/FlorianParty/Projet_LPA2/builds/278957389

**Comment by EdemosBonboy** [comment]
https://travis-ci.org/EdemosBonboy/projet/builds/279290011

**Comment by mlbnc** [comment]
https://travis-ci.org/mlbnc/projet/builds/279223552

**Comment by MLucile** [comment]
https://travis-ci.org/MLucile/Projet_LPA2/builds/279470960

**Comment by Cladlink** [comment]
https://travis-ci.org/Cladlink/lpa2_projet/builds/279475034

**Comment by HADHRI** [comment]
https://travis-ci.org/HADHRI/Projet_LPA2/builds/279666749

**Comment by dbissari** [comment]
https://travis-ci.org/dbissari/projet/builds/279850099

**Comment by zahrijaa140** [comment]
https://travis-ci.org/zahrijaa140/Projet/builds/279898714

**Comment by Integrale18** [comment]
https://travis-ci.org/Integrale18/projetlpa/jobs/281236705

**Comment by zikas96** [comment]
https://travis-ci.org/zikas96/projet/builds/280562185

**Comment by claude25** [comment]
https://travis-ci.org/claude25/Project/builds/281368354

**Comment by edwardAGE4** [comment]
https://travis-ci.org/edwardAGE4/projet/builds/281397241

**Comment by HamzaAma** [comment]
https://travis-ci.org/HamzaAma/projet

**Comment by BorisBrogle** [comment]
https://travis-ci.org/BorisBrogle/LPA2_Projet/builds/281691066

**Comment by RodolphePonthon** [comment]
https://travis-ci.org/RodolphePonthon/Projet/builds/281691636

**Comment by science162** [comment]
https://travis-ci.org/science162/ProjetLPA2/builds/281749891

**Comment by Anium** [comment]
https://travis-ci.org/Anium/projet/builds/282028212

**Comment by Theoche** [comment]
https://travis-ci.org/Theoche/projet/builds/282726788

**Comment by wdjousse** [comment]
https://travis-ci.org/wdjousse/projet/builds/282731096

**Comment by donald116** [comment]
https://travis-ci.org/donald116/projet/builds/282731059

**Comment by arona504** [comment]
https://travis-ci.org/arona504/projet

**Comment by YannPoncet** [comment]
https://travis-ci.org/YannPoncet/projet/builds/283748176

**Comment by bollytachi** [comment]
https://travis-ci.org/bollytachi/Project/builds/283986095

**Comment by balmajoe** [comment]
https://travis-ci.org/balmajoe/projet/jobs/284108664

**Comment by apardieu** [comment]
https://travis-ci.org/apardieu/projet/builds/284300879

**Comment by LPA2-Automne2016** [comment]
Good Job all pour le premie devoir !
Je ferme l'issue.
