### ISSUE TITLE
livrer la page des students

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#2]
livrer la page des students sous heroku poster
-  l'url de la page
- le build travis 

**ATTENTION pas de db:migrate à la main !!!! le mettre dans le .travis**

**Comment by McKay1717** [comment]
Page Heroku : https://stark-atoll-89746.herokuapp.com/students/
Build : https://travis-ci.org/McKay1717/projet/builds/351654317

**Comment by LeGoffMael** [comment]
Build Travis : https://travis-ci.org/LeGoffMael/projet/builds/351657539
App Heroku : https://projet-app.herokuapp.com/students

**Comment by aurelienblais** [comment]
App Heroku : https://projet-blais.herokuapp.com/
Build Travis : https://travis-ci.org/aurelienblais/projet/builds/351662438

**Comment by antvalla** [comment]
**VALLA Antoine**

- https://vallapp.herokuapp.com
- https://travis-ci.org/antvalla/projet/builds/351658913

**Comment by jertran** [comment]
Page Heroku : https://web-app-ruby-utbm.herokuapp.com/students
Build Travis : https://travis-ci.org/jertran/projet/builds/351664579

**Comment by remyguillaumot** [comment]
Rémy Guillaumot

- App Heroku : https://guarded-reaches-12454.herokuapp.com/students
- Build Travis : https://travis-ci.org/remyguillaumot/projet/builds/351663110

**Comment by trivetroff** [comment]
**Tristan VETROFF**

- App Heroku: https://projet-lpa2-tvet.herokuapp.com/students
- Build Travis: https://travis-ci.org/trivetroff/projet/builds/351704436

**Comment by Novardon** [comment]
**Soufiane EL HIDAOUI**

-  App Heroku: https://young-eyrie-42378.herokuapp.com/students
-  Build Travis: https://travis-ci.org/Novardon/projet/builds/351904603

**Comment by AnthonyPierrat** [comment]
Anthony Pierrat

- App Heroku: https://projet-pierrat.herokuapp.com/students
- Build Travis: https://travis-ci.org/AnthonyPierrat/projet/jobs/351946065

**Comment by sakalypse** [comment]
Kevin Limacher

- App Heroku : https://projet-kevin-limacher.herokuapp.com/students

- Build Travis : https://travis-ci.org/sakalypse/projet/builds/351994993

**Comment by lordtel** [comment]
Nour-eddine BRAHMI

- App Heroku : https://projet-nb.herokuapp.com/students

- Build Travis : https://travis-ci.org/lordtel/projet/builds/351662405

**Comment by ThibaudREY** [comment]
App Heroku : [https://projet-3.herokuapp.com/students](https://projet-3.herokuapp.com/students)
Build Travis : [https://travis-ci.org/ThibaudREY/projet/builds/353073678](https://travis-ci.org/ThibaudREY/projet/builds/353073678)

**Comment by Paul-AntoinePechmeja-Richard** [comment]
Paul-Antoine Pechmeja--Richard

Heroku : https://projetpapr.herokuapp.com/students
Build     : https://travis-ci.org/Paul-AntoinePechmeja-Richard/projet/builds/351663542

**Comment by yaman0** [comment]
PRETOT Nathan :

Travis : https://travis-ci.org/yaman0/projet_LPA2/builds/352716181
Heroku : https://projetlpa2111.herokuapp.com/students

**Comment by smdu57** [comment]
Simon Manfredini

Travis : https://travis-ci.org/smdu57/projet/builds/353306443
Heroku : https://webapp-simon.herokuapp.com/students

**Comment by adavid1** [comment]
Axel DAVID

Travis : https://travis-ci.org/adavid1/projet/builds/352767676?utm_source=email&utm_medium=notification
Heroku : https://fierce-crag-27323.herokuapp.com/students

**Comment by atomicpunkk** [comment]
Cussey Lucas

travis: https://travis-ci.org/atomicpunkk/projet-lpa2/builds/353316771
heroku: https://projet-lc.herokuapp.com/students

**Comment by Eowaobwyn** [comment]
**Corentin DIEVAL**

Travis : https://travis-ci.org/Eowaobwyn/projet/builds/354051933
Heroku : https://projet-1.herokuapp.com/students

**Comment by FARGANI** [comment]
Travis : https://travis-ci.org/FARGANI/Projet/builds/354290031
Heroku : https://prog-fargani.herokuapp.com/

**Comment by Nitale** [comment]
Travis : https://travis-ci.org/Nitale/projet/builds/354456563
Heroku : https://dashboard.heroku.com/apps/boiling-savannah-35761

**Comment by celier** [comment]
Robin CÉLIÉ-GRIMAL
Travis    : https://travis-ci.org/celier/projet/builds/353761772
Heroku : https://serene-badlands-54352.herokuapp.com/students

**Comment by thoory** [comment]
Thomas ORY
Travis: https://travis-ci.org/thoory/projet/builds/354455158
Heroku: https://projet-thoory-lpa2.herokuapp.com/

**Comment by VDucroux** [comment]
Valentin DUCROUX
Travis: https://travis-ci.org/VDucroux/projet/builds/351654825
Heroku: https://projet-vd.herokuapp.com/

**Comment by warmcy** [comment]
**Cylia HARBANE**
**Travis:** https://travis-ci.org/warmcy/Projet/builds
**Heroku:** https://projet-harbane.herokuapp.com/students

**Comment by MNanko** [comment]
**Nanko Mohamed**

Page Heroku : https://project-nanko.herokuapp.com/
Build : https://travis-ci.org/MNanko/Project/builds/355881733
