### ISSUE TITLE
Modifier la page d'accueil de l'application

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#2]
Modifier la page d'accueil de l'application : ne plus afficher la page par défaut de rails
- utiliser la configuration de Rails pour créer un paramètre supplémentaire contenant le nom du propriétaire  : http://guides.rubyonrails.org/configuring.html#custom-configuration
- créer un controleur dédié à la page d'accueil
- ne garder qu'une seule méthode dans le controlleur, dédiée à la page d'accueil
- modifier le routage pour pointer vers cette nouvelle page http://guides.rubyonrails.org/routing.html#using-root
- créer la page web pour afficher le ou les noms des propriétaires de l'application

**Comment by LPA2-Automne2016** [comment]
Plus intégrer le lancement de la la commande rake db:migrate dans le CI afin de lancer la migration de la base de données

**Comment by Katravan** [comment]
Voici le lien de mon heroku : https://murmuring-badlands-28165.herokuapp.com/
Et le lien du build : https://travis-ci.org/Katravan/projet/builds/212423762
Florian Inard

**Comment by Transrian** [comment]
Bonjour,
Voici le lien de mon heroku : https://warm-falls-14630.herokuapp.com/
Et le lien du build travis : https://travis-ci.org/Transrian/projet/builds/212433929
Valentin Bourdier

**Comment by QuentinSimonU** [comment]
Bonjour,
Voici le lien de mon heroku : https://safe-reaches-89463.herokuapp.com/
Et le lien du build travis : https://travis-ci.org/QuentinSimonU/projet/builds/213326045
Quentin Simon

**Comment by lisamaison** [comment]
Bonjour,
Voici le lien de mon heroku : https://young-sea-93159.herokuapp.com/
Et le lien de mon build travis : https://travis-ci.org/lisamaison/projet/builds/213335737
Lisa Bessone

**Comment by VMoniz** [comment]
Bonjour,
Heroku : https://quiet-ravine-16218.herokuapp.com/
Build : https://travis-ci.org/VMoniz/projet/builds/213335736

Valentine Moniz

**Comment by Globuss** [comment]
Bonjour,
Voici le lien de mon heroku : https://limitless-hamlet-44082.herokuapp.com/
Et le lien du build travis : https://travis-ci.org/Globuss/projet
Théo Pierret

**Comment by souley221** [comment]
Bonjour, 
Voici le lien de mon heroku : https://whispering-hamlet-75434.herokuapp.com/
E le lien de mon travis : https://travis-ci.org/souley221/projet

Souleymane SOLLY

**Comment by jacmartinelli** [comment]
Bonjour,
Voici le lien de mon heroku : https://quiet-lowlands-40226.herokuapp.com/students
Et le lien de mon travis : https://travis-ci.org/jacmartinelli/projet
Jacques MARTINELLI

**Comment by MeyerEsther** [comment]
Bonjour,
Voici le lien de mon heroku: https://murmuring-headland-50346.herokuapp.com/
Et le lien de mon travis: https://travis-ci.org/MeyerEsther/projet
Meyer Esther

**Comment by quentinpmf** [comment]
Bonjour,
Voici le lien de mon heroku: https://glacial-caverns-69838.herokuapp.com/
Et le lien de mon travis: https://travis-ci.org/quentinpmf/projet/builds/212422248
Quentin BOUDINOT

**Comment by remipe-utbm** [comment]
Bonjour,
Voici le lien de mon Heroku : https://project-lpa2.herokuapp.com/
Et le lien de mon travis : https://travis-ci.org/remipe-utbm/projet/jobs/213824886

Rémi Pereira

**Comment by thibaut-monrouzeau** [comment]
Bonjour,
Voici le lien de mon Heroku : https://agile-beyond-94050.herokuapp.com/
Voici le lien de mon Travis : https://travis-ci.org/thibaut-monrouzeau/projet
Thibaut Monrouzeau

**Comment by dlcadrien** [comment]
Bonjour,
**Heroku :** https://enigmatic-peak-33586.herokuapp.com/
**Travis :** https://travis-ci.org/dlcadrien/projet/builds/214720057
Adrien Delcourt

**Comment by Aurelien-Py** [comment]
Bonjour,
Heroku : https://guarded-tundra-95985.herokuapp.com/
Travis : https://travis-ci.org/Aurelien-Py/projet/jobs/213859118

Aurélien PY

**Comment by NBarras** [comment]
Bonjour,
Travis : https://travis-ci.org/NBarras/projet/builds/213551782
Heroku : https://still-ridge-60791.herokuapp.com/

Noé Barras

**Comment by alexandrebm74** [comment]
Bonjour,
Travis : https://travis-ci.org/alexandrebm74/projet/builds/214763066
Heroku : https://desolate-gorge-80275.herokuapp.com/

**Comment by GuillaumePriou** [comment]
Bonjour,
Voici les liens vers mon espace de travail :
Travis : https://travis-ci.org/GuillaumePriou/projet
Heroku : https://salty-crag-46216.herokuapp.com/
Guillaume

**Comment by Achrafeu** [comment]
Bonjour,
Voici les liens vers mon espace de travail :
Travis : https://travis-ci.org/Achrafeu/projet/builds/214782146
Heroku : https://ancient-eyrie-10775.herokuapp.com/students/new
Achraf

**Comment by Sgliere** [comment]
Bonjour,
Lien du build Travis : https://travis-ci.org/Sgliere/projet/builds/214816779
lien du site via Heroku : https://lpa2.herokuapp.com/

Swann GLIERE

**Comment by sye9286** [comment]
Bonjour,
voici mes liens
    Heroku : https://applp71.herokuapp.com/students
    Travis : https://travis-ci.org/sye9286/projet/builds/214839883

Sheng YE

**Comment by LPA2-Automne2016** [comment]
bravo à tous,
encore sans faute !

A samedi pour de folles aventures
