### ISSUE TITLE
afficher la météo

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#3]
lorsque l'on affiche une ville , affichier la météo avec la ville.

Attention : ne pas stocker la météo dans la BDD!

la gem qui permet de rechercher la météo :
https://github.com/vigosan/forecast_io

Pour ce faire 

creer un compte sous darksky
recuperer le token
modifier le model de la ville
mettre en place la meteo
afficher les éléments de base de cette météo

**Comment by LPA2-Automne2016** [comment]
ATTENTION :exclamation: 
La librairie darksky-ruby a été dépréciée et ne fonctionne plus !

il faut utiliser celle ci : https://github.com/vigosan/forecast_io

**Comment by aurelienblais** [comment]
Build : https://travis-ci.org/aurelienblais/projet/builds/354784215
App : https://projet-blais.herokuapp.com/
CodeClimate : https://codeclimate.com/github/aurelienblais/projet

Endpoints API : 
GET /api/towns
GET /api/towns/:id

**Comment by jertran** [comment]
Build: https://travis-ci.org/jertran/projet/builds/355817928
App: https://web-app-ruby-utbm.herokuapp.com/
CodeClimate: https://codeclimate.com/github/jertran/projet
[![Test Coverage](https://api.codeclimate.com/v1/badges/46935bcc9dc763dc2595/test_coverage)](https://codeclimate.com/github/jertran/projet/test_coverage)
[![Maintainability](https://api.codeclimate.com/v1/badges/46935bcc9dc763dc2595/maintainability)](https://codeclimate.com/github/jertran/projet/maintainability)
![travis](https://travis-ci.org/jertran/projet.svg?branch=master)

**Comment by antvalla** [comment]
**Antoine VALLA**

- Build -> https://travis-ci.org/antvalla/projet/builds/355831186
- App -> https://vallapp.herokuapp.com/
- Code Climate -> https://codeclimate.com/github/antvalla/projet

**Comment by ThibaudREY** [comment]
Build: [https://travis-ci.org/ThibaudREY/projet/builds/356128967](https://travis-ci.org/ThibaudREY/projet/builds/356128967)
App: [https://projet-3.herokuapp.com/towns](https://projet-3.herokuapp.com/towns)
CodeClimate: [https://codeclimate.com/github/ThibaudREY/projet](https://codeclimate.com/github/ThibaudREY/projet)

**Comment by celier** [comment]
Robin CÉLIÉ-GRIMAL
Build : https://travis-ci.org/celier/projet/builds/356316288
App: https://serene-badlands-54352.herokuapp.com/towns
CodeClimate: https://codeclimate.com/github/celier/projet

**Comment by Novardon** [comment]
**Soufiane EL HIDAOUI**

Build :https://travis-ci.org/Novardon/projet/builds/356343206
App: https://young-eyrie-42378.herokuapp.com/
CodeClimate: https://codeclimate.com/github/Novardon/projet

**Comment by Novardon** [comment]
**Soufiane EL HIDAOUI**

Build : https://travis-ci.org/Novardon/projet/builds/356441485
App: https://young-eyrie-42378.herokuapp.com/
CodeClimate: https://codeclimate.com/github/Novardon/projet

**Comment by LeGoffMael** [comment]
**Maël LE GOFF**
Build: https://travis-ci.org/LeGoffMael/projet/builds/355879026
App: https://projet-app.herokuapp.com/
CodeClimate: https://codeclimate.com/github/LeGoffMael/projet

**Comment by adavid1** [comment]
**Axel DAVID**
Build : https://travis-ci.org/adavid1/projet/builds/356747009
App : https://projet1-adavid.herokuapp.com/
CodeClimate : https://codeclimate.com/github/adavid1/projet

**Comment by lordtel** [comment]
**Nour-eddine BRAHMI**

Build : https://travis-ci.org/lordtel/projet/builds/356754151
App : https://projet-nb.herokuapp.com
CodeClimate : https://codeclimate.com/github/lordtel/projet

**Comment by smdu57** [comment]
Simon MANFREDINI

Build : https://travis-ci.org/smdu57/projet/builds/356913026
App : https://webapp-simon.herokuapp.com/cities
CodeClimate : https://codeclimate.com/github/smdu57/projet

**Comment by sakalypse** [comment]
Kevin LIMACHER

Build : https://travis-ci.org/sakalypse/projet/builds/357014629
App : https://projet-kevin-limacher.herokuapp.com/
CodeClimate : https://codeclimate.com/github/sakalypse/projet

**Comment by atomicpunkk** [comment]
CUSSEY Lucas
Travis : https://travis-ci.org/atomicpunkk/projet-lpa2/builds/357039629
App : https://projet-lc.herokuapp.com/towns
CodeClimate : https://codeclimate.com/github/atomicpunkk/projet-lpa2
[![Build Status](https://travis-ci.org/atomicpunkk/projet-lpa2.svg?branch=master)](https://travis-ci.org/atomicpunkk/projet-lpa2)
[![Maintainability](https://api.codeclimate.com/v1/badges/9129bb18f90bedb7f400/maintainability)](https://codeclimate.com/github/atomicpunkk/projet-lpa2/maintainability)
[![Test Coverage](https://api.codeclimate.com/v1/badges/9129bb18f90bedb7f400/test_coverage)](https://codeclimate.com/github/atomicpunkk/projet-lpa2/test_coverage)

**Comment by Nitale** [comment]
PUGET Mathieu
Travis : https://travis-ci.org/Nitale/projet/builds/357130137
App : https://boiling-savannah-35761.herokuapp.com/towns

**Comment by FARGANI** [comment]
Travis : https://travis-ci.org/FARGANI/Projet/builds/357388414
App : https://prog-fargani.herokuapp.com/
[![Maintainability](https://api.codeclimate.com/v1/badges/7d2d0eca74479c2d2800/maintainability)](https://codeclimate.com/github/FARGANI/Projet/maintainability)
[![Test Coverage](https://api.codeclimate.com/v1/badges/7d2d0eca74479c2d2800/test_coverage)](https://codeclimate.com/github/FARGANI/Projet/test_coverage)

**Comment by yaman0** [comment]
PRETOT Nathan

Build -> [![Build Status](https://travis-ci.org/yaman0/projet_LPA2.svg?branch=master)](https://travis-ci.org/yaman0/projet_LPA2)
Codeclimate -> [![Build Status](https://travis-ci.org/yaman0/projet_LPA2.svg?branch=master)](https://travis-ci.org/yaman0/projet_LPA2) [![Maintainability](https://api.codeclimate.com/v1/badges/760fa6fd3b4c4d4b5946/maintainability)](https://codeclimate.com/github/yaman0/projet_LPA2/maintainability)
App -> https://projetlpa2111.herokuapp.com/towns
Github -> https://github.com/yaman0/projet_LPA2

**Comment by AnthonyPierrat** [comment]
Anthony PIERRAT

Build Travis : https://travis-ci.org/AnthonyPierrat/projet/builds/357479766
[![Build Status](https://travis-ci.org/AnthonyPierrat/projet.svg?branch=master)](https://travis-ci.org/AnthonyPierrat/projet)
Code Climate 
<a href="https://codeclimate.com/github/AnthonyPierrat/projet/maintainability"><img src="https://api.codeclimate.com/v1/badges/5843d99e02f4e50b1792/maintainability" /></a>
<a href="https://codeclimate.com/github/AnthonyPierrat/projet/test_coverage"><img src="https://api.codeclimate.com/v1/badges/5843d99e02f4e50b1792/test_coverage" /></a>

Heroku App : https://projet-pierrat.herokuapp.com/towns

**Comment by remyguillaumot** [comment]
Travis : https://travis-ci.org/remyguillaumot/projet/builds/357502007
App : http://remy-guillaumot.herokuapp.com
CodeClimate : https://codeclimate.com/github/remyguillaumot/projet

**Comment by McKay1717** [comment]
Travis : https://travis-ci.org/McKay1717/projet/builds/357515355?utm_source=github_status&utm_medium=notification
App :  https://stark-atoll-89746.herokuapp.com/

[![Maintainability](https://api.codeclimate.com/v1/badges/76966c2599a8544d1d2a/maintainability)](https://codeclimate.com/github/McKay1717/projet/maintainability)

[![Test Coverage](https://api.codeclimate.com/v1/badges/76966c2599a8544d1d2a/test_coverage)](https://codeclimate.com/github/McKay1717/projet/test_coverage)

**Comment by MNanko** [comment]
NANKO Mohamed

**## Build** : https://travis-ci.org/MNanko/Project-weather/builds/357597127
**## App** : https://project-weather.herokuapp.com/towns
**## CodeClimate** : https://codeclimate.com/github/MNanko/Project-weather

![Build Status](https://travis-ci.org/MNanko/Project.svg?branch=master)
[![Maintainability](https://api.codeclimate.com/v1/badges/cb4b0e6212ef28bd2536/maintainability)](https://codeclimate.com/github/MNanko/Project-weather/maintainability)
[![Test Coverage](https://api.codeclimate.com/v1/badges/cb4b0e6212ef28bd2536/test_coverage)](https://codeclimate.com/github/MNanko/Project-weather/test_coverage)

**Comment by warmcy** [comment]
Travis : https://travis-ci.org/warmcy/Projet/builds/357591482
App : https://projet-harbane.herokuapp.com/towns
CodeClimate : https://codeclimate.com/github/warmcy/Projet

**Comment by rokhaya-sonko** [comment]
**Rokhaya SONKO**

**Build Travis : https://travis-ci.org/rokhaya-sonko/Projet/builds
App : https://rokhayasnk.herokuapp.com
Code climate :** https://codeclimate.com/github/rokhaya-sonko/Projet

**Comment by thoory** [comment]
Thomas ORY

Build Travis: https://travis-ci.org/thoory/projet/builds/357092099
App: https://projet-thoory-lpa2.herokuapp.com/

**Comment by trivetroff** [comment]
Tristan VETROFF:

Build Travis: https://travis-ci.org/trivetroff/projet/builds/356852005
App: https://projet-lpa2-tvet.herokuapp.com/towns

**Comment by LPA2-Automne2016** [comment]
Bravo à tous, bon travail !

mention spéciale à @warmcy pour l'iframe, c'était pas demandé, mais bien vu et bien joué.
Autre mention spéciale à @trivetroff : la jolie ville de myString.... pas forcément bien géocodée :monkey_face:
