### ISSUE TITLE
déployer l'appli anguar vers github

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#4]
Activer travis sur le nouveau projet

dans le le build, faire ng build --env prod  ( attention au href, a cause de github )

déployer le resultat sur github pages
https://docs.travis-ci.com/user/deployment/pages/

**Comment by aurelienblais** [comment]
Lien Github Pages : https://aurelienblais.github.io/projet-front/
Build Travis : https://travis-ci.org/aurelienblais/projet-front/builds/357815818

**Comment by AnthonyPierrat** [comment]
Github Pages : https://anthonypierrat.github.io/town-frontend/
Build Travis : https://travis-ci.org/AnthonyPierrat/town-frontend/builds/358589850

[![Build Status](https://travis-ci.org/AnthonyPierrat/town-frontend.svg?branch=master)](https://travis-ci.org/AnthonyPierrat/town-frontend)
[![Maintainability](https://api.codeclimate.com/v1/badges/1a9dabf8c0ccfd7c1103/maintainability)](https://codeclimate.com/github/AnthonyPierrat/town-frontend/maintainability)

**Comment by adavid1** [comment]
**Axel David**
Page Guithub : https://adavid1.github.io/projet_front-end/
Build Travis : https://travis-ci.org/adavid1/projet_front-end/builds/358784508

**Comment by trivetroff** [comment]
**Tristan VETROFF**
Page Github: https://trivetroff.github.io/projet-front/
Build Travis: https://travis-ci.org/trivetroff/projet-front

**Comment by Novardon** [comment]
**Soufiane EL HIDAOUI**

Page Github: https://novardon.github.io/projet_front_end/
Build Travis:  https://travis-ci.org/Novardon/projet_front_end/builds/364524562

**Comment by thoory** [comment]
**Thomas ORY**
Page Github: https://thoory.github.io/ProjetFrontEnd/
Build Travis: https://travis-ci.org/thoory/ProjetFrontEnd/builds/358825240

**Comment by yaman0** [comment]
**Nathan PRETOT**
Page Github : https://yaman0.github.io/projet_LPA2_frontend/
Build Travis : https://travis-ci.org/yaman0/projet_LPA2_frontend/builds/365686422

**Comment by atomicpunkk** [comment]
Lucas CUSSEY
Page Github : https://atomicpunkk.github.io/projet-frontend/
Build Travis : https://travis-ci.org/atomicpunkk/projet-frontend/builds/365689339

**Comment by lordtel** [comment]
**Nour-eddine BRAHMI**
Page Github : https://lordtel.github.io/projet-frontend/
Build travis : https://travis-ci.org/lordtel/projet-frontend/builds/365962104

**Comment by antvalla** [comment]
**Antoine VALLA**

- **Page Github** : https://antvalla.github.io/projet-node-lpa2/
- **Build Travis** : https://travis-ci.org/antvalla/projet-node-lpa2/builds/366197413

**Comment by FARGANI** [comment]
- Page Github : https://fargani.github.io/Project-Front/
- Build Travis : https://travis-ci.org/FARGANI/Project-Front/builds/366230701

**Comment by MNanko** [comment]
Mohamed NANKO

Page Github : https://mnanko.github.io/Project-front/
Build Travis : https://travis-ci.org/MNanko/Project-front/builds/366234129

**Comment by remyguillaumot** [comment]
- Page Github : https://remyguillaumot.github.io/projet-frontend/
- Build Travis : https://travis-ci.org/remyguillaumot/projet-frontend/builds/366231980

**Comment by celier** [comment]
Page Github : https://celier.github.io/angular-front/
Build Travis : https://travis-ci.org/celier/angular-front/builds/366231351

**Comment by McKay1717** [comment]
Page: https://mckay1717.github.io/LPA2_Frontend/
Build: https://travis-ci.org/McKay1717/LPA2_Frontend/builds/366256978

**Comment by jertran** [comment]
TRAN Jeremy

Page GitHub: https://jertran.github.io/front-angular/
Build: https://travis-ci.org/jertran/front-angular/builds/366286924

**Comment by sakalypse** [comment]
LIMACHER kévin

Page GitHub : https://sakalypse.github.io/projet_front_end/
Build : https://travis-ci.org/sakalypse/projet_front_end/builds/366300358

**Comment by Nitale** [comment]
PUGET Mathieu

Page GitHub: https://github.com/Nitale/projet_nodeJS
Build: https://travis-ci.org/Nitale/projet_nodeJS

**Comment by LeGoffMael** [comment]
Le Goff Maël

Page GitHub: https://legoffmael.github.io/projet-frontend/
Build Travis: https://travis-ci.org/LeGoffMael/projet-frontend/builds/366333884

**Comment by smdu57** [comment]
Manfredini Simon

Page Github : https://smdu57.github.io/projet2-web/town/
Build Travis : https://travis-ci.org/smdu57/projet2-web/builds/365523401

**Comment by rokhaya-sonko** [comment]
Rokhaya Sonko
 **Github Page** : https://rokhaya-sonko.github.io/projet-angular/
**Build Travis** : https://travis-ci.org/rokhaya-sonko/projet-angular

**Comment by LPA2-Automne2016** [comment]
Un sans faute pour ceux qui ont rendu le devoir !
Très bon boulot, je vois qu'angular inspire pas mal de monde.
