### ISSUE TITLE
Faire disparaitre le warning de dépendance obsolète

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#4]
Github indique que notre projet contient des dépendances obsoletes
mettre à niveau ces dépendances pour ne plus avoir de problème.

Attention ne pas faire de montée majeure des gems : que le strict nécessaire pour ne plus avoir le problème.

poster le ien vers le github complété.

**Comment by Anthex** [comment]
[repo](https://github.com/Anthex/projet)

**Comment by dbissari** [comment]
[Repository](https://github.com/dbissari/projet)

**Comment by Cladlink** [comment]
[lien](https://github.com/Cladlink/lpa2_projet)

**Comment by EdemosBonboy** [comment]
<a href="https://github.com/EdemosBonboy/projet">Repo github</a>

**Comment by HamzaAma** [comment]
https://github.com/HamzaAma/Tests

**Comment by Theoche** [comment]
[github](https://github.com/Theoche/projet)

**Comment by FlorianParty** [comment]
[Github](https://github.com/FlorianParty/Projet_LPA2)

**Comment by MLucile** [comment]
[Github](https://github.com/MLucile/Projet_LPA2)

**Comment by mlbnc** [comment]
[Github](https://github.com/mlbnc/lpa2projet)

**Comment by arona504** [comment]
[Github](https://github.com/arona504/projet)

**Comment by donald116** [comment]
https://github.com/donald116/projet

**Comment by claude25** [comment]
https://github.com/claude25/Project

**Comment by HADHRI** [comment]
https://github.com/HADHRI/lpa

**Comment by wdjousse** [comment]
https://github.com/wdjousse/projet

**Comment by balmajoe** [comment]
[Github](https://github.com/balmajoe/projet)

**Comment by zikas96** [comment]
https://github.com/zikas96/projet/

**Comment by Integrale18** [comment]
https://github.com/Integrale18/projetlpa

**Comment by Anium** [comment]
https://github.com/Anium/projet

**Comment by FlorianR-UTBM** [comment]
[Github](https://github.com/FlorianR-UTBM/projet)

**Comment by BorisBrogle** [comment]
-> [Github](https://github.com/BorisBrogle/LPA2_Projet)

**Comment by YannPoncet** [comment]
[Github](https://github.com/YannPoncet/projet)

**Comment by RodolphePonthon** [comment]
[Github](https://github.com/RodolphePonthon/Projet)

**Comment by edwardAGE4** [comment]
https://github.com/edwardAGE4/projet

**Comment by bollytachi** [comment]
https://github.com/bollytachi/bolly
