### ISSUE TITLE
Afficher la météo en live depuis le webservice

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#5]
Créer un service
interroger l'API à l'adresse suivante https://lpa2sgadot.herokuapp.com/towns/3.json
livrer la page sur github pages

poster l'url github et le  CI

**Comment by ThibaudREY** [comment]
Lien Github Pages : [https://thibaudrey.github.io/projet-front/](https://thibaudrey.github.io/projet-front/)
Build Travis : [https://travis-ci.org/ThibaudREY/projet-front/builds/358861938](https://travis-ci.org/ThibaudREY/projet-front/builds/358861938)

**Comment by aurelienblais** [comment]
Lien Github Pages : https://aurelienblais.github.io/projet-front/
Build Travis : https://travis-ci.org/aurelienblais/projet-front/builds/366424585

**Comment by adavid1** [comment]
Lien Github Pages : https://adavid1.github.io/projet_front-end/
Build Travis : https://travis-ci.org/adavid1/projet_front-end/builds/368778984


[![Build Status](https://travis-ci.org/adavid1/projet_front-end.svg?branch=master)](https://travis-ci.org/adavid1/projet_front-end)
[![Maintainability](https://api.codeclimate.com/v1/badges/24ed16c00c4c06591fc5/maintainability)](https://codeclimate.com/github/adavid1/projet_front-end/maintainability)

**Comment by Nitale** [comment]
Lien Github Pages : https://nitale.github.io/projet_nodeJS/
Build Travis : https://travis-ci.org/Nitale/projet_nodeJS/builds/369201913

**Comment by yaman0** [comment]
**PRETOT Nathan**
**URL site frontend =>** https://yaman0.github.io/projet_LPA2_frontend/
**Build Travis =>** https://travis-ci.org/yaman0/projet_LPA2_frontend/builds/369211050

**Comment by trivetroff** [comment]
Tristan VETROFF
Page Github: https://trivetroff.github.io/projet-front/
Build Travis: https://travis-ci.org/trivetroff/projet-front/builds/369212989

**Comment by MNanko** [comment]
Mohamed NANKO
Page Github: https://mnanko.github.io/Project-front/
Build Travis: https://travis-ci.org/MNanko/Project-front/builds/369214527

**Comment by atomicpunkk** [comment]
Cussey Lucas
URL site frontend : https://atomicpunkk.github.io/projet-frontend/
Build Travis :  https://travis-ci.org/atomicpunkk/projet-frontend/builds/369124509

**Comment by FARGANI** [comment]
Page Github: https://fargani.github.io/projet-font/
Build Travis: https://travis-ci.org/FARGANI/projet-font/builds/369231503

**Comment by McKay1717** [comment]
Nicolas IUNG
Page Git : https://mckay1717.github.io/LPA2_Frontend/
Le Build : https://travis-ci.org/McKay1717/LPA2_Frontend/builds/369257017

**Comment by sakalypse** [comment]
Kévin LIMACHER
Page Git : https://sakalypse.github.io/projet_front_end/
Build : https://travis-ci.org/sakalypse/projet_front_end/builds/369309992

**Comment by AnthonyPierrat** [comment]
Anthony PIERRAT
GithubPages : https://anthonypierrat.github.io/town-frontend/
Build Travis : https://travis-ci.org/AnthonyPierrat/town-frontend/builds/358860773

**Comment by antvalla** [comment]
**Antoine VALLA**

- Page GitHub....https://antvalla.github.io/projet-node-lpa2/
- Build Travis.......https://travis-ci.org/antvalla/projet-node-lpa2/builds/369320068

**Comment by remyguillaumot** [comment]
- Page Github : https://remyguillaumot.github.io/projet-frontend/
- Build : https://travis-ci.org/remyguillaumot/projet-frontend/builds/368809348

**Comment by LeGoffMael** [comment]
- Page Github : https://legoffmael.github.io/projet-frontend/
- Build : https://travis-ci.org/LeGoffMael/projet-frontend/builds/369363019

**Comment by thoory** [comment]
Ory Thomas

Page Github: https://thoory.github.io/ProjetFrontEnd/
Travis: https://travis-ci.org/thoory/ProjetFrontEnd/builds/368805096

**Comment by jertran** [comment]
Jeremy TRAN

Page GitHub : https://jertran.github.io/front-angular/
Build : https://travis-ci.org/jertran/front-angular/builds/369413031

**Comment by Eowaobwyn** [comment]
DIEVAL CORENTIN

PAGE GITHUB : https://eowaobwyn.github.io/Angular-FrontEnd/
BUILD : https://travis-ci.org/Eowaobwyn/Angular-FrontEnd/builds/366284206

**Comment by Novardon** [comment]
Soufiane EL HIDAOUI

Page Github: https://novardon.github.io/projet_front_end/
Build Travis: https://travis-ci.org/Novardon/projet_front_end/builds/369417924

**Comment by VDucroux** [comment]
Valentin DUCROUX

Page Github : https://vducroux.github.io/projet_multimedia/
Build Travis : https://travis-ci.org/VDucroux/projet_multimedia/builds/369429254

**Comment by rokhaya-sonko** [comment]
Rokhaya Sonko

Github page : https://rokhaya-sonko.github.io/projet-angular/
Travis Build : https://travis-ci.org/rokhaya-sonko/projet-angular

**Comment by warmcy** [comment]
**Cylia HARBANE**
**Github page :** https://warmcy.github.io/projet-angular/
**Travis Build :** https://travis-ci.org/warmcy/projet-angular

**Comment by LPA2-Automne2016** [comment]
Ce devoir conclut notre dernière scéance ensembles.
