### ISSUE TITLE
terminer l'implémentation de la gem VCR.

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#5]
Remettre en état les tests :

a l'aide de la gem VCR, intercepter les appels HTTP de vos tests et rendre vos tests indépendants des réponses d'internet.

rendre : le travis ( attention à bien mettre un lien vers le build du commit, pas un lien général)

**Comment by mlbnc** [comment]
https://travis-ci.org/mlbnc/lpa2projet

**Comment by dbissari** [comment]
[Travis](https://travis-ci.org/dbissari/projet/builds/310427162)

**Comment by FlorianParty** [comment]
[Travis](https://travis-ci.org/FlorianParty/Projet_LPA2/builds/310427338)

**Comment by claude25** [comment]
https://travis-ci.org/claude25/Project/builds/310427260

**Comment by YannPoncet** [comment]
[Travis](https://travis-ci.org/YannPoncet/projet/builds/310455665)

**Comment by Cladlink** [comment]
[travis](https://travis-ci.org/Cladlink/lpa2_projet/builds/311276667)

**Comment by HADHRI** [comment]
[travis](https://travis-ci.org/HADHRI/lpa/builds/311313999)

**Comment by apardieu** [comment]
https://travis-ci.org/apardieu/projet/builds/310454697

J'en profite pour caser le GitHub avec la montée de version que j'avais oublié de rendre samedi dernier
https://github.com/apardieu/projet

**Comment by zahrijaa140** [comment]
[https://travis-ci.org/zahrijaa140/Projet/builds/313068476](url)

**Comment by MLucile** [comment]
[travis](https://travis-ci.org/MLucile/Projet_LPA2/builds/313083003)

**Comment by Integrale18** [comment]
https://travis-ci.org/Integrale18/projetlpa/builds/313450871

**Comment by BorisBrogle** [comment]
[Travis](https://travis-ci.org/BorisBrogle/LPA2_Projet/builds/310455453)

**Comment by RodolphePonthon** [comment]
[Travis](https://travis-ci.org/RodolphePonthon/Projet/builds/310455616)

**Comment by donald116** [comment]
[travis](https://travis-ci.org/donald116/projet)

**Comment by HamzaAma** [comment]
[travis](https://travis-ci.org/HamzaAma/lpa2/builds/313693260)

**Comment by Anthex** [comment]
[Travis](https://travis-ci.org/Anthex/projet/builds/313718960)

**Comment by zikas96** [comment]
https://travis-ci.org/zikas96/projet/jobs/313718551

**Comment by edwardAGE4** [comment]
https://travis-ci.org/edwardAGE4/projet/jobs/310456863

**Comment by FlorianR-UTBM** [comment]
[Travis](https://travis-ci.org/FlorianR-UTBM/projet/builds/313017661)

**Comment by balmajoe** [comment]
[Travis](https://travis-ci.org/balmajoe/projet/builds/313743064)

**Comment by Anium** [comment]
https://travis-ci.org/Anium/projet/builds/313779899

**Comment by Theoche** [comment]
[Travis](https://travis-ci.org/Theoche/projet)

**Comment by EdemosBonboy** [comment]
<a href="https://travis-ci.org/EdemosBonboy/projet/builds/313865441">Travis</a>

**Comment by science162** [comment]
https://travis-ci.org/science162/ProjetLPA2
https://dashboard.heroku.com/apps/immense-hollows-35607

**Comment by wdjousse** [comment]
https://travis-ci.org/wdjousse/projet

**Comment by bollytachi** [comment]
https://travis-ci.org/bollytachi/bolly

**Comment by LPA2-Automne2016** [comment]
Bon  boulot à tous !
