### ISSUE TITLE
Faire appel à une API depuis rails

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#6]
Créer un controleur dans l'application faisant appel à l'API de prévision météo

https://github.com/darkskyapp/forecast-ruby

afficher les prévisions depuis une des pages du controleur

pour la partie geocoding : cf Nominatim

**Comment by LPA2-Automne2016** [comment]
Suite aux modifications de ce jour en cours, reste à faire : 
- modifier le model city.rb pour créer une fonction de recherche de la météo
- modifier le controller city_controller.rb pour ajouter l'appel de cette fonction dans la fonction d'affichage d'une ville pour y inclure cet appel à la météo
- modifier la vue d'affichage de la ville pour y afficher le résultat de la météo.
- déployer tout cela sous github

**Comment by aomnes** [comment]
Voici mon appli avec la météo:
https://meteo-lpa2.herokuapp.com/cities
https://travis-ci.org/aomnes/projet_ruby
https://github.com/aomnes/projet_ruby

**Comment by dsyouness** [comment]
Voici mon app la météo ça marche (temperature+summary)
Heroku : https://murmuring-springs-27327.herokuapp.com/cities
Travis : https://travis-ci.org/dsyouness/projet (Erreur :The command "bundle exec rake" exited with 1 ) erreur lié à  l'intégration de la météo 
Git : https://github.com/dsyouness/projet

**Comment by LPA2-Automne2016** [comment]
bien joué @dsyouness , merci à toi et à @aomnes.

beau travail

**Comment by xAlban** [comment]
Voici l'ajout du forecast dans notre appli cities :
https://salty-fortress-48990.herokuapp.com/cities
https://travis-ci.org/xAlban/projet/builds/168273826 (erreur lié à l'intégration du forecast)
https://github.com/xAlban/projet

**Comment by med-amiine** [comment]
Voici pour l'intégration de l'API forecast :
 https://secret-sierra-80991.herokuapp.com/cities
https://travis-ci.org/med-amiine/projet ( même erreur que les autres qui est lié à l'intégration d'une API )
https://github.com/med-amiine/projet

**Comment by HuangMichel** [comment]
Ajout du gem 'forecast_io'
https://studentliste.herokuapp.com/cities

https://travis-ci.org/HuangMichel/projet/builds(error de l'API)

**Comment by Zilliq11** [comment]
Voici l'appli avec la météo :
Travis : https://travis-ci.org/Zilliq11/projet
Heroku : https://lpa2-zilliq11-nitrous.herokuapp.com/cities
Git : https://github.com/Zilliq11/projet

**Comment by mtetou** [comment]
Voici mes modifications pour la météo:
Travis : https://travis-ci.org/mtetou/projet
Heroku : https://projet-tresortou409095.codeanyapp.com/cities/1
Github : https://github.com/mtetou/projet

**Comment by cfall** [comment]
API depuis rails: 
https://travis-ci.org/cfall/projet_LPA2
https://secure-ocean-53691.herokuapp.com/cities
https://github.com/cfall/projet_LPA2

**Comment by safaael** [comment]
Voici les liens de l'app:
https://github.com/safaael/projet
https://travis-ci.org/safaael/projet
https://gentle-peak-77971.herokuapp.com/cities

**Comment by wnansseu** [comment]
Voici mon appli qui fonctionne sauf pour les test travis-ci:
https://salty-lowlands-89256.herokuapp.com/cities
https://travis-ci.org/wnansseu/projet_LPA2/

**Comment by oacardoso** [comment]
Voila mon lien Git
https://github.com/oacardoso/LPA2_PROJET

**Comment by assaadkenaan** [comment]
Voici mes liens de l'app : 

Heroku : https://agile-island-78481.herokuapp.com/cities
Travis : https://travis-ci.org/assaadkenaan/projet  ( même erreur que les autres qui est lié à l'intégration d'une API)

**Comment by WEI-Jialiang** [comment]
Voila les liens de l'app :
https://pacific-chamber-88805.herokuapp.com/cities
https://travis-ci.org/WEI-Jialiang/projet

**Comment by LIUJINGYUYVES** [comment]
Bonjour, monsieur. Voici les liens de l'app :
https://github.com/LIUJINGYUYVES/projet2
https://travis-ci.org/LIUJINGYUYVES/projet2/builds/169201311
https://aqueous-shore-60208.herokuapp.com/cities

**Comment by ASARIR** [comment]
bonjour monsieur , voici les liens pour mon application 
https://limitless-dusk-16472.herokuapp.com/cities
https://github.com/ASARIR/projet

**Comment by LPA2-Automne2016** [comment]
@mtetou je viens d'ouvrir ton application
attention je me prends une grosse erreur et rien ne marche
tu as probablement un truc qui ne va pas dans ton appli.

**Comment by xiaoma27** [comment]
bonjour monsieur , voici mes liens pour application 
https://github.com/xiaoma27/projet
https://hidden-caverns-70071.herokuapp.com/cities
https://travis-ci.org/xiaoma27/projet(je ne sais pas pourquoi ça marche pas)

**Comment by jwang04** [comment]
bonjour, monsieur
https://vast-dusk-15260.herokuapp.com/cities
https://travis-ci.org/jwang04/projet/branches
https://github.com/jwang04/projet

**Comment by qxj1210** [comment]
Bonjour, Monsieur
Voici mon application
https://hidden-ridge-15509.herokuapp.com/cities
https://travis-ci.org/qxj1210/projet     mais je ne sais pas pourquoi ça marche pas sur travis

**Comment by MaoYiwen** [comment]
bonjour monsieur,
https://mysterious-everglades-14523.herokuapp.com/cities
https://travis-ci.org
https://github.com/MaoYiwen/projet

**Comment by YUZHENFEI** [comment]
Voici, les liens : 
https://shrouded-refuge-36462.herokuapp.com/cities
https://travis-ci.org/YUZHENFEI/projet

**Comment by juyulu** [comment]
voici les liens
https://powerful-anchorage-27402.herokuapp.com/cities
https://travis-ci.org/juyulu/projet

**Comment by Yzxwyydn** [comment]
voici les liens
https://limitless-tor-17231.herokuapp.com/cities
https://travis-ci.org/Yzxwyydn/projet/builds/171611167

**Comment by echoise** [comment]
voici les liens
https://blooming-tundra-76491.herokuapp.com/cities
https://travis-ci.org/echoise/projet

**Comment by yidabao** [comment]
voici mes liens:
https://infinite-everglades-50604.herokuapp.com/cities
https://travis-ci.org/yidabao/projet

**Comment by MARui22** [comment]
c'est le lien de app
https://aqueous-earth-99850.herokuapp.com/cities
https://travis-ci.org/MARui22/projet

**Comment by fadina5** [comment]
c'est le lien de l'appli :
https://projetlp.herokuapp.com/cities
j'ai un problème avec travis

**Comment by LPA2-Automne2016** [comment]
date limite
