### ISSUE TITLE
uploader l'appli angular vierge (juste la page standard) vers github pages

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#6]
une fois l'appli générée, utiliser le package suivant :
https://github.com/angular-schule/angular-cli-ghpages

pour remonter et héberger votre page angular sous github pages

**Comment by science162** [comment]
https://science162.github.io/projetAngular/

**Comment by EdemosBonboy** [comment]
<a href="https://edemosbonboy.github.io/angular_lpa2/">Page github</a>

**Comment by FlorianR-UTBM** [comment]
[Page Angular Github](https://florianr-utbm.github.io/lpa2-angular/)

**Comment by dbissari** [comment]
[Page](https://dbissari.github.io/angular/)

**Comment by FlorianParty** [comment]
[Page Github](https://florianparty.github.io/Angular-Projet-LPA2/)

**Comment by zahrijaa140** [comment]
[Page Github ](https://zahrijaa140.github.io/Angular/)

**Comment by arona504** [comment]
[Projetangular](https://arona504.github.io/projetangular/)

**Comment by balmajoe** [comment]
[angular](https://balmajoe.github.io/angular/)

**Comment by claude25** [comment]
https://claude25.github.io/angular/

**Comment by donald116** [comment]
https://donald116.github.io/angular/

**Comment by bollytachi** [comment]
https://bollytachi.github.io/angular/

**Comment by zikas96** [comment]
https://zikas96.github.io/angular

**Comment by mlbnc** [comment]
https://mlbnc.github.io/lpa2projet_angular/

**Comment by MLucile** [comment]
https://mlucile.github.io/Angular_LPA2/

**Comment by Cladlink** [comment]
https://cladlink.github.io/testAngular/

**Comment by RodolphePonthon** [comment]
[Github page](https://rodolpheponthon.github.io/LPA2_AngularProject/)

**Comment by BorisBrogle** [comment]
[Github.io link](https://borisbrogle.github.io/LPA2_Angular/angular/)

**Comment by apardieu** [comment]
https://apardieu.github.io/angular/

**Comment by YannPoncet** [comment]
[Github.io](https://yannponcet.github.io/LPA2_angular/)

**Comment by Anium** [comment]
https://anium.github.io/angular/

**Comment by edwardAGE4** [comment]
<a href="https://edwardage4.github.io/ProjetNodeJs/">Lien github </a>

**Comment by Integrale18** [comment]
https://integrale18.github.io/angular/

**Comment by Anthex** [comment]
[Lien](https://anthex.github.io/angular/)

**Comment by HADHRI** [comment]
https://hadhri.github.io/angular/

**Comment by HamzaAma** [comment]
https://hamzaama.github.io/angularJs/

**Comment by Theoche** [comment]
[lien GitHub page](https://theoche.github.io/AngularV2/)

**Comment by wdjousse** [comment]
https://wdjousse.github.io/angular/
