### ISSUE TITLE
Faire appel à une API depuis rails

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#6]
Créer un controleur dans l'application faisant appel à l'API de prévision météo

https://github.com/darkskyapp/forecast-ruby

afficher les prévisions depuis une des pages du controleur

pour la partie geocoding : cf Nominatim

**Comment by LPA2-Automne2016** [comment]
bon reflexe : utilsier le fichier des secrets pour mettre  le token de l'api meteo
http://guides.rubyonrails.org/4_1_release_notes.html#config-secrets-yml

mettre des variables d'environnement (cf exemple) et les définir dans travis et heroku

**Comment by Transrian** [comment]
Bonjour,
Voici le lien de mon heroku : https://warm-falls-14630.herokuapp.com/towns
Voici le lien de mon travis : https://travis-ci.org/Transrian/projet/jobs/215037725
Valentin Bourdier

**Comment by VMoniz** [comment]
Bonjour, 
Heroku : https://quiet-ravine-16218.herokuapp.com/cities/1
Travis : https://travis-ci.org/VMoniz/projet/builds/216278032
Valentine Moniz

**Comment by lisamaison** [comment]
Bonjour,
Voici le lien de mon heroku : https://warm-falls-14630.herokuapp.com/towns
Voici le lien de mon travis : https://travis-ci.org/lisamaison/projet/builds/216279513
Bessone Lisa

**Comment by remipe-utbm** [comment]
Bonjour ! 

Voilà le lien de Heroku : https://project-lpa2.herokuapp.com/towns
Et voici le lien de Travis : https://travis-ci.org/remipe-utbm/projet/jobs/216316274

Rémi Pereira

**Comment by thibaut-monrouzeau** [comment]
Bonjour,
Mon lien Heroku : https://agile-beyond-94050.herokuapp.com/
Mon lien Travis : https://travis-ci.org/thibaut-monrouzeau/projet/builds/218491733

Thibaut Monrouzeau

**Comment by Aurelien-Py** [comment]
Bonjour,
Mon lien Heroku : https://guarded-tundra-95985.herokuapp.com/locations
Mon lien Travis : https://travis-ci.org/Aurelien-Py/projet/jobs/218480054

Aurélien PY

**Comment by dlcadrien** [comment]
Bonjour,
Heroku : https://enigmatic-peak-33586.herokuapp.com/cities
Travis : https://travis-ci.org/dlcadrien/projet/builds/218482826
Adrien Delcourt

**Comment by MeyerEsther** [comment]
Bonjour,
Voilà le lien de Heroku : https://murmuring-headland-50346.herokuapp.com/villes
Et voici le lien de Travis : https://travis-ci.org/MeyerEsther/projet/builds/218813913
Meyer Esther

**Comment by QuentinSimonU** [comment]
Bonjour,
Voilà le lien de Heroku : https://safe-reaches-89463.herokuapp.com/cities/1
Et voici le lien de Travis : https://travis-ci.org/QuentinSimonU/projet/builds/218836170
Quentin Simon

**Comment by souley221** [comment]
Bonjour,
Voilà le lien de mon application sur Heroku : https://whispering-hamlet-75434.herokuapp.com/cities
Et le lien de Travis : https://travis-ci.org/souley221/projet/builds
Solly Souleymane

**Comment by Globuss** [comment]
Bonjour,
Voilà le lien de mon application sur Heroku : https://limitless-hamlet-44082.herokuapp.com/towns
Théooooooooooooooooooooo

**Comment by sye9286** [comment]
Bonjour,
Heroku : https://applp71.herokuapp.com/cities
Travis : https://travis-ci.org/sye9286/projet/builds/219334379
Sheng YE

**Comment by jacmartinelli** [comment]
Hello,
[Heroku](https://quiet-lowlands-40226.herokuapp.com/towns)
[Travis](https://travis-ci.org/jacmartinelli/projet/builds)
Jacques

**Comment by quentinpmf** [comment]
Bonjour,
Voilà le lien de Heroku : https://glacial-caverns-69838.herokuapp.com/towns
Et voici le lien de Travis : https://travis-ci.org/quentinpmf/projet/builds/219764091
Quentin Boudinot

**Comment by Sgliere** [comment]
Bonjour,
Voilà le lien de Heroku : https://lpa2.herokuapp.com/towns
Et voici le lien de Travis : https://travis-ci.org/Sgliere/projet
Quentin Boudinot

**Comment by GuillaumePriou** [comment]
Bonjour,
Voilà le lien de Heroku : https://salty-crag-46216.herokuapp.com/towns
Et voici le lien de Travis : https://travis-ci.org/GuillaumePriou/projet/builds/219863841
Guillaume Priou

**Comment by alexandrebm74** [comment]
Bonjour,
Lien Heroku : https://desolate-gorge-80275.herokuapp.com/villes
Lien Travis : https://travis-ci.org/alexandrebm74/projet/builds/219868240
Alexandre BOURDILLAS-MACEY

**Comment by NBarras** [comment]
lien heroku : https://still-ridge-60791.herokuapp.com/villes
lien travis : https://travis-ci.org/NBarras/projet/builds/219968590
Barras Noé

**Comment by Achrafeu** [comment]
Bonjour,
lien heroku : http://project_1-achrafel-mancouri963031.codeanyapp.com:3000/cities
lien travis : https://travis-ci.org/Achrafeu/projet/builds/222108038
Merci à vous.
ELMANCOURI Achraf

**Comment by LPA2-Automne2016** [comment]
Bon travail à tous !
mention spéciale à @MeyerEsther @Globuss @quentinpmf @Transrian qui sont allés plus loin au niveau du CSS que demandé ! 

Particulièrement @MeyerEsther  et @Transrian :+1:
