### ISSUE TITLE
Créer une SPA

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet#7]
Une SPA signifie en anglais "Single Page Application" Il s'agit d'une appli web dont le rendu se fait exclusivement dans le navigateur et pour laquelle toutes les informations sont cherchées au travers de webservices JSON.

Doc et example disponible ici
https://www.meteor.com/tutorials/angular/creating-an-app

**Comment by LPA2-Automne2016** [comment]
a l'aide des ressources angular : https://docs.angularjs.org/api/ngResource/service/$resource

appeler /students/:id.json pour récupérer la liste des étudiants

**Comment by aomnes** [comment]
Voici mon appli:
https://meteo-lpa2.herokuapp.com/angular-seed/app/index
https://meteo-lpa2.herokuapp.com/students
https://travis-ci.org/aomnes/projet_ruby/

**Comment by gorille** [comment]
@aomnes toujours premier sur la breche !
Bon travail Antoine

**Comment by HuangMichel** [comment]
Voici les liens: https://travis-ci.org/HuangMichel/projet
http://studentliste.herokuapp.com/angular-seed/app#!/Students

**Comment by xAlban** [comment]
Voici les liens de mon appli et du travis (avec du bootstrap): 
https://travis-ci.org/xAlban/projet/builds/170745396
https://salty-fortress-48990.herokuapp.com/angular-seed/app

**Comment by WEI-Jialiang** [comment]
Voici les liens:
https://fierce-escarpment-75559.herokuapp.com/angular-seed/app/index
https://travis-ci.org/WEI-Jialiang/projet

**Comment by zeyizhou** [comment]
Voici les liens : 
https://guarded-sands-29623.herokuapp.com/angular-seed/app/index
https://travis-ci.org/zeyizhou/projet

**Comment by jwang04** [comment]
bonjour monsieur
https://travis-ci.org/jwang04/projet
https://aqueous-forest-43046.herokuapp.com/angular-seed/app/index#!/view1

**Comment by qxj1210** [comment]
Bonjour monsieur
voici les liens:
https://ancient-oasis-71484.herokuapp.com/angular-seed/app/index#!/view1
https://travis-ci.org/qxj1210/projet

**Comment by YUZHENFEI** [comment]
bonsoir
voici les liens
https://radiant-bastion-90055.herokuapp.com/angular-seed/app/index#!/view1
https://travis-ci.org/YUZHENFEI/projet

**Comment by MaoYiwen** [comment]
Voici les liens
https://still-ridge-61084.herokuapp.com/angular-seed/app/index#!/view1
https://travis-ci.org/MaoYiwen/projet

**Comment by juyulu** [comment]
voici les liens
https://powerful-anchorage-27402.herokuapp.com/angular-seed/app/index#!/view1
https://travis-ci.org/juyulu/projet

**Comment by Yzxwyydn** [comment]
voici les liens
https://limitless-tor-17231.herokuapp.com/angular-seed/app/index#!/view1
https://travis-ci.org/Yzxwyydn/projet/builds/171612502

**Comment by cfall** [comment]
Utilisation SPA:
https://projet-fallsheikh78341.codeanyapp.com/angular-seed/app/index
https://travis-ci.org/cfall/projet_LPA2

**Comment by Zilliq11** [comment]
Bonsoir, voici mon appli :
https://lpa2-zilliq11-nitrous.herokuapp.com/angular-seed/app/index
https://lpa2-zilliq11-nitrous.herokuapp.com/students
https://travis-ci.org/Zilliq11/projet

**Comment by cfall** [comment]
Creation SPA avec $resource
https://secure-ocean-53691.herokuapp.com/Angular-seed/app/index
https://secure-ocean-53691.herokuapp.com/users
https://travis-ci.org/cfall/projet_LPA2

**Comment by echoise** [comment]
voici les liens
https://blooming-tundra-76491.herokuapp.com/angular-seed/app/index#!/view1
https://travis-ci.org/echoise/projet

**Comment by LIUJINGYUYVES** [comment]
Bonjour monsieur, voici les liens:
https://aqueous-shore-60208.herokuapp.com/angular-seed/app/index#!/view1
https://travis-ci.org

**Comment by yidabao** [comment]
voici les liens:
https://infinite-everglades-50604.herokuapp.com/angular-seed/app/index#!/view1
https://travis-ci.org/yidabao/projet/builds/172131119

**Comment by xiaoma27** [comment]
Bonsoir monsieur, voici les liens:
https://travis-ci.org/xiaoma27/projet/builds/171224061
https://blooming-tor-11219.herokuapp.com/angular-seed/app/index#!/view1

**Comment by MARui22** [comment]
bonsoir, ce sont les liens: 
https://travis-ci.org/MARui22/projet
https://aqueous-earth-99850.herokuapp.com/angular-seed/app/index#!/view1

**Comment by safaael** [comment]
Bonsoir,
les liens : 
https://gentle-peak-77971.herokuapp.com/angular-seedcopy/app/index#!/view1
https://travis-ci.org/safaael/projet

**Comment by wnansseu** [comment]
Bonsoir 
mes liens
https://morning-hamlet-77829.herokuapp.com/angular-seed/app/index#!/view1
https://travis-ci.org/wnansseu/projet_LPA2
https://morning-hamlet-77829.herokuapp.com/students

**Comment by assaadkenaan** [comment]
Bonsoir,

Voici mes liens : 
Travis : https://travis-ci.org/assaadkenaan/projet
Heroku :https://agile-island-78481.herokuapp.com/angular-seed/app/index.html#!/view1

**Comment by mtetou** [comment]
Bonjour,
les liens pour ma SPA:
Travis : https://travis-ci.org/mtetou/projet
Heroku : https://radiant-refuge-58204.herokuapp.com/angular-seed/app/index#!/view1

**Comment by LPA2-Automne2016** [comment]
date limite

**Comment by ASARIR** [comment]
Bonjour mon appli viens de fonctionner voila mes liens : 
travis : https://travis-ci.org/ASARIR/projet
heroku : https://limitless-dusk-16472.herokuapp.com/angular-seed/app/index.html#!/view1

**Comment by oacardoso** [comment]
https://shrouded-fortress-67001.herokuapp.com/angula/app/index#!/view1
https://travis-ci.org/oacardoso/LPA2_PROJET/builds/177899133
Voila Voila

**Comment by med-amiine** [comment]
https://secret-sierra-80991.herokuapp.com/angular-seed/app/index.html#!/view1
https://travis-ci.org/med-amiine/projet

**Comment by dsyouness** [comment]
Bonjour
Heroku : https://floating-shore-49279.herokuapp.com/angular-sed/app/index.html#!/view1
Travis : https://travis-ci.org/dsyouness/Projet

**Comment by fadina5** [comment]
bonsoir mon lien:
https://projet-fantanathalie854751.codeanyapp.com/angular-seed/app/index
